### ISSUE TITLE
Issues modifying users

### ISSUE THREAD

**Issue by estrohm** [j-colson419/assignforce181210#71]
When modifying a user through setup, it refuses to save users and gives a useless error message: "Please enter a value" at the top of the page.

After lots of digging and some ad hoc Apex, I found that there is a custom field "Available__c" on the user object that is marked as required. For users created after installing the package containing this field, there is no problem since it specifies a default value. However, for users created before installing the package (e.g. the original sysadmin) this results in being unable to modify any of the user's fields, including activating/deactivating them.

**Comment by ddgreer889** [comment]
To fix this issue, change the User setup so that it works and document the changes. These changes will need to be sent to Jessica in order to ensure that the changes are reflected in the production org.
